spring:
  profiles:
    active:
    - dev

---
server:
  port: 8888
spring:
  profiles: dev
  application:
    name: microserviceconfig-dev
my:
  desc: desc-dev
---
server:
  port: 9999
spring:
  profiles: test
  application:
    name: microserviceconfig-test
my:
  desc: desc-test